import os

from dotenv import load_dotenv

load_dotenv()

PATH_MEASUREMENT_SUMMARY_PATH = os.getenv("PATH_MEASUREMENT_SUMMARY")
PATH_MEASUREMENT_ITEM_INFO_PATH = os.getenv("PATH_MEASUREMENT_ITEM_INFO")
PATH_MEASUREMENT_INFO_PATH = os.getenv("PATH_MEASUREMENT_INFO")
PATH_MEASUREMENT_STATION_INFO_PATH = os.getenv("PATH_MEASUREMENT_STATION_INFO")
