from columns import TIME_COLUMNS, STATION_COLUMNS, INSTRUMENT_STATUS_COLUMNS, MERGED_SENSOR_COLUMNS, POLLUTANT_COLUMNS, \
    UNIT_OF_MEASUREMENT_COLUMNS, POLLUTANT_CLASS_COLUMNS

TABLES_MAP = {
    "time": TIME_COLUMNS,
    "station": STATION_COLUMNS,
    "instrument_status": INSTRUMENT_STATUS_COLUMNS,
    "merged_sensor": MERGED_SENSOR_COLUMNS,
    "pollutant": POLLUTANT_COLUMNS,
    "pollutant_class": POLLUTANT_CLASS_COLUMNS,
    "unit_of_measurement": UNIT_OF_MEASUREMENT_COLUMNS
}
